spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: odatour-waiting-system
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  sql:
    init:
      mode: always
